window.tailwind = {
  config: {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "pure-white": "#FFFFFF",
                        "error": "#ffb4ab",
                        "on-surface-variant": "#c4c7c8",
                        "secondary-fixed-dim": "#c6c6c6",
                        "on-secondary": "#303030",
                        "inverse-primary": "#5d5f5f",
                        "secondary-container": "#474747",
                        "on-primary": "#2f3131",
                        "on-secondary-fixed": "#1b1b1b",
                        "surface-container-low": "#1c1b1b",
                        "primary": "#ffffff",
                        "primary-fixed-dim": "#c6c6c7",
                        "surface-tint": "#c6c6c7",
                        "surface": "#141313",
                        "inverse-on-surface": "#313030",
                        "primary-fixed": "#e2e2e2",
                        "void-black": "#0A0A0A",
                        "surface-variant": "#353434",
                        "hazard-red": "#CD2C44",
                        "on-surface": "#e5e2e1",
                        "error-container": "#93000a",
                        "tertiary-fixed": "#e2e2e2",
                        "curse-green": "#00A441",
                        "inverse-surface": "#e5e2e1",
                        "on-error": "#690005",
                        "surface-dim": "#141313",
                        "tertiary": "#ffffff",
                        "surface-container-highest": "#353434",
                        "primary-container": "#e2e2e2",
                        "on-tertiary-container": "#636565",
                        "surface-container-lowest": "#0e0e0e",
                        "tertiary-container": "#e2e2e2",
                        "secondary-fixed": "#e2e2e2",
                        "on-tertiary": "#2f3131",
                        "on-error-container": "#ffdad6",
                        "surface-container-high": "#2a2a2a",
                        "on-secondary-fixed-variant": "#474747",
                        "tertiary-fixed-dim": "#c6c6c7",
                        "off-white": "#F6F7F8",
                        "on-background": "#e5e2e1",
                        "outline": "#8e9192",
                        "surface-bright": "#3a3939",
                        "on-secondary-container": "#b5b5b5",
                        "on-primary-fixed-variant": "#454747",
                        "on-primary-container": "#636565",
                        "on-tertiary-fixed-variant": "#454747",
                        "on-tertiary-fixed": "#1a1c1c",
                        "background": "#141313",
                        "secondary": "#c6c6c6",
                        "border-muted": "#1F1F1F",
                        "on-primary-fixed": "#1a1c1c",
                        "surface-container": "#201f1f",
                        "outline-variant": "#444748"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.25rem",
                        "lg": "0.5rem",
                        "xl": "0.75rem",
                        "full": "9999px"
                    },
                    "spacing": {
                        "unit": "4px",
                        "margin-mobile": "16px",
                        "gutter": "24px",
                        "margin-desktop": "64px",
                        "section-gap": "120px"
                    },
                    "fontFamily": {
                        "headline-md": ["Barlow Condensed"],
                        "body-lg": ["DM Sans"],
                        "display-hero": ["Barlow Condensed"],
                        "body-md": ["DM Sans"],
                        "display-hero-mobile": ["Barlow Condensed"],
                        "label-caps": ["Montserrat"],
                        "headline-lg": ["Barlow Condensed"],
                        "price-mono": ["DM Sans"],
                        "script": ["Ephesis", "cursive"]
                    },
                    "fontSize": {
                        "headline-md": ["24px", { "lineHeight": "28px", "letterSpacing": "0.05em", "fontWeight": "700" }],
                        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                        "display-hero": ["80px", { "lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "800" }],
                        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                        "display-hero-mobile": ["48px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "700" }],
                        "headline-lg": ["40px", { "lineHeight": "44px", "letterSpacing": "0.02em", "fontWeight": "700" }],
                        "price-mono": ["16px", { "lineHeight": "24px", "fontWeight": "700" }]
                    }
                },
            },
        }
};
